# Generated by Django 3.2.12 on 2023-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computergeneration',
            old_name='ram',
            new_name='RAM',
        ),
        migrations.AlterField(
            model_name='computergeneration',
            name='generation',
            field=models.CharField(max_length=20),
        ),
    ]
