# Generated by Django 3.2.12 on 2023-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20230929_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerbrand',
            name='logo',
            field=models.ImageField(null=True, upload_to='uploadimages/'),
        ),
    ]
