# Generated by Django 3.2.12 on 2023-09-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_alter_computerbrand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computergeneration',
            name='generation',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
