# Generated by Django 3.2.12 on 2023-10-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_rename_ram_computergeneration_ram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computergeneration',
            old_name='ram',
            new_name='RAM',
        ),
    ]
